### ISSUE TITLE
Start a new game.

### ISSUE THREAD

**Issue by honnert57** [skiadas/LegendOfParkerAuditorium#1]
Starting a new game

**Comment by honnert57** [comment]
- [ ] Set Location to Building Menu
- [ ] User action start needs created
- [ ] Building Menu Class needs created

**Comment by SRK400KRZ** [comment]
@honnert57 
Is this if-statement correct?
It won't pass _canCreateGame_ test in _InteractorTest_.                                               
<img width="526" alt="Screen Shot 2020-10-27 at 16 26 06" src="https://user-images.githubusercontent.com/30650175/97358710-07bb8400-1872-11eb-8675-d3b4e7a0472a.png">

**Comment by honnert57** [comment]
You can comment it out for now i know he said not to comment out code but it worked for me but if it doesnt work for you ill fix it

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by honnert57** [comment]
I think its because i dont initialize game in the test so my test might be wrong

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by skiadas** [comment]
@honnert57 I think the check in the "if" is simply the reverse from what you want to. Don't you want that exception to be thrown if there is a game going on already (i.e. game is NOT null)?

There are however good reasons to not have the system behave that way anyway. Why should a user not be able to simply start a new game and abandon the game they were playing at the time? Isn't this the action that will be called in such case as well? In that eventuality, game will at the time of the call hold the old game.
