### ISSUE TITLE
Restrict access to buildings based on inventory

### ISSUE THREAD

**Issue by JoshElfers** [skiadas/LegendOfParkerAuditorium#5]

**Comment by skiadas** [comment]
- [ ] item one 
- [ ] item two

**Comment by carrollm22** [comment]
- [ ] Implement inventory 
- [ ] Check inventory for number of keys
- [ ] If number is correct allow access to certain buildings 
- [ ] Check location to see if you are in the right spot to enter the building

**Comment by SRK400KRZ** [comment]
- [ ] TODO: move the function to Inventory class

https://github.com/skiadas/LegendOfParkerAuditorium/blob/3761645a181d00793ed7dc4f9a3d9cb58df761aa/src/core/Game.java#L113-L115
